version: '3.1'
services:
  ghost-mysql:
    image: docker.io/bitnami/mysql:8.0
    volumes:
      - 'mysql-ghost-cms-data:/bitnami/mysql'
    environment:
      MYSQL_CLIENT_DATABASE_ROOT_PASSWORD: QpsSnTM5wb
      MYSQL_ROOT_PASSWORD: QpsSnTM5wb
      MYSQL_CLIENT_CREATE_DATABASE_NAME: ghost-cms
      MYSQL_USER: ghost-cms
      MYSQL_PASSWORD: QpsSnTM5wb
      MYSQL_DATABASE: ghost-cms
  ghost-cms:
    image: docker.io/bitnami/ghost:5
    ports:
      - '80:2368'
    volumes:
      - 'ghost-cms-data:/bitnami/ghost'
    depends_on:
      - ghost-mysql
    environment:
      GHOST_DATABASE_HOST: ghost-mysql
      GHOST_DATABASE_PORT_NUMBER: 3306
      GHOST_DATABASE_NAME: ghost-cms
      GHOST_DATABASE_USER: ghost-cms
      GHOST_DATABASE_PASSWORD: QpsSnTM5wb
volumes:
  mysql-ghost-cms-data: {}
  ghost-cms-data: {}